apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Terraformer
  annotations:
    github.com/project-slug: abuzarshabab/Terraformer
spec:
  type: other
  lifecycle: unknown
  owner: guests
